version: 2.1

orbs:
  nx: nrwl/nx@1.6.2

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout


      - run: npm ci --legacy-peer-deps
      - nx/set-shas:
          main-branch-name: 'main'

      - run: npx nx affected -t lint test build

workflows:
  version: 2

  ci:
    jobs:
      - main
